### ISSUE TITLE
kitchan-salt cannot download salt packages on debian/jessie

### ISSUE THREAD

**Issue by maratsh** [saltstack/kitchen-salt#120] opened 2017-07-09 18:46 UTC
The problem is because of lack apt-transport-https packages
```
-----> Converging <default-xbtsyslog-debian-jessie64>...
       Preparing files for transfer
       Preparing salt-minion
       Preparing pillars into /srv/pillar
       Preparing grains into /etc/salt/grains
       Preparing state collection
       neither collection_name or formula have been set, assuming this is a pre-built collection
       Preparing state_top
       Preparing scripts into /etc/salt/scripts
       sh: 1: salt-call: not found
-----> Configuring apt repo for salt 2016.11.3
       deb https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/2016.11.3 jessie main
       downloading https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub
         to file /tmp/repo.key
       trying wget...
       OK
E: The method driver /usr/lib/apt/methods/https could not be found.
       N: Is the package apt-transport-https installed?
-----> Installing salt-minion (2016.11.3)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
       python-support is already the newest version.
       The following packages were automatically installed and are no longer required:
         libyaml-0-2 python-jinja2 python-mako python-markupsafe python-msgpack
         python-yaml
       Use 'apt-get autoremove' to remove them.
       0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
       E: Unable to locate package salt-minion
       E: Unable to locate package salt-common
       sh: 1: salt-call: not found
       No salt-minion installed, install must have failed!!
       salt_install = apt
       salt_url = https://bootstrap.saltstack.com
       bootstrap_options = 
       salt_version = 2016.11.3
       salt_apt_repo = https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest
       salt_apt_repo_key = https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub
       salt_ppa = ppa:saltstack/salt

```

```
source 'https://rubygems.org'

gem "test-kitchen", '>=1.2.1'
gem "kitchen-vagrant"
gem "unf"
gem "kitchen-salt", ">=0.0.27"

```

**Comment by gtmanfred** [comment] 2017-08-18 14:30
It actually appears that the problem is that 

```
        salt_apt_repo: 'https://repo.saltstack.com/apt/ubuntu/16.04/amd64/',
        salt_apt_repo_key: 'https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub',
```

These variables default to being set for ubuntu, so you will have to configure them.  I will work on making them be more agnostic by default.

**Comment by gtmanfred** [comment] 2017-08-19 02:51
So, it looks like this would be much more difficult in ruby than I was expecting.

Until I can figure out a better way to get the distribution, the code name, and the version, without having to use lsb_release.  I am going to list this as a `Won't Fix for Now`

and you will have to specify the correct `salt_apt_repo`
```
salt_apt_repo: 'https://repo.saltstack.com/apt/debian/8/amd64/',
salt_apt_repo_key: 'https://repo.saltstack.com/apt/debian/8/amd64/latest/SALTSTACK-GPG-KEY.pub',
```

**Closed as completed by gtmanfred** 2017-08-19 02:51 UTC
Labels: bug, Won't Fix for Now

**Comment by maratsh** [comment] 2017-09-23 20:12
Why you don't use bootstrap.sh script?
