### ISSUE TITLE
run in debug mode

### ISSUE THREAD

**Issue by ssplatt** [saltstack/kitchen-salt#33] opened 2015-11-25 13:51 UTC
is it possible to get the highstate to run in debug mode? the ability to add `-l debug` to salt-call would help track down troublesome bugs in code.

**Comment by ssplatt** [comment] 2015-11-25 14:45
i just found `cmd << " --log-level=#{config[:log_level]}"` in the code, which isn't documented anywhere, but setting `log_leve: debug` in the kitchen file doesn't seem to actually do anything from what i can see.  

I also just tried adding `default_config :log_level, "debug"` to no avail.

**Comment by twmartin** [comment] 2016-09-16 14:54
Tried doing this today and I was able to get debug output from salt by setting `log_level: debug` in the `provisioner` options of my `.kitchen.yml` file.

**Comment by ek9** [comment] 2017-02-04 16:20
I can verify that setting `log_level` in `provisioner` options (`.kitchen.yml`) works as intended. I've also submited a PR to add this to Provisioner Doc ( #88 ). This can be closed once #88 is merged.

**Closed as completed** 2017-02-06 12:38 UTC
